### ISSUE TITLE
Plot as a component?

### ISSUE THREAD

**Issue by danieljfarrell** [fabiofranchino/integrating-vega-with-vue#2]
Thanks for much for this demo project, if helped me get stated. Ok trying to integrate vega into an existing typescript project that uses components.

Typescript is optional for the plot component (mixed JavaScript/typescript is fine), but wondering how you would go about modifying this  to be a Vue component?

**Comment by abusedmedia** [comment]
Hi @danieljfarrell 

Quickly, if you want to create a Vue component that renders a Vega-Lite chart using Vega-Embed, just wrap [this chunk](https://github.com/fabiofranchino/integrating-vega-with-vue/blob/6e4a925eafc913793be0f10c0c787d4f7a4ba45b/src/App.vue#L67-L74) in a Component and expose a property for the `def` object, isn't it?

**Comment by danieljfarrell** [comment]
Thanks you! Will try this out.
